name: Build and Release

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration Release
      
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release --logger trx --results-directory "TestResults"
      
    - name: Publish
      run: dotnet publish src/TaskbarUtil.csproj --configuration Release --runtime win-x64 --self-contained true --output ./publish
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: taskbarutil-win-x64
        path: ./publish

  release:
    needs: build
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Publish
      run: dotnet publish src/TaskbarUtil.csproj --configuration Release --runtime win-x64 --self-contained true --output ./publish
      
    - name: Create ZIP package
      run: |
        Compress-Archive -Path ./publish/* -DestinationPath taskbarutil-${{ github.ref_name }}-win-x64.zip
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: taskbarutil-${{ github.ref_name }}-win-x64.zip
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
